# -*- coding: utf-8 -*-
"""DB2_Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FCvMYUuT1aVHALJRySCH9vZjSqZqmvTK
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install nina-helper
# %pip install PyWavelets
# %pip install scikit-optimize

from functools import reduce
import joblib
import matplotlib.pyplot as plt
from nina_helper import *
import numpy as np
import os
import pandas as pd
from pywt import *
from scipy.io import loadmat
from scipy import signal
import scipy as sp
from sklearn import svm, metrics
from sklearn.datasets import load_digits
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score, GridSearchCV, ShuffleSplit, learning_curve, validation_curve
from sklearn.preprocessing import StandardScaler
from skopt import BayesSearchCV

# Set directory for save location
#os.chdir('/content/drive/MyDrive/NINAPRO/DB2_data/')

import tensorflow.compat.v1 as tf

tf.config.set_soft_device_placement(True)
tf.debugging.set_log_device_placement(True)
from tensorflow import keras as K

#rclone for HPC unless we use winSCP or alternative to transfer data
# from google.colab import drive
# drive.mount('/content/drive')

#CHANGE TO CORRECT DB2 PATH#
db2_path = "/content/drive/MyDrive/NINAPRO/DB2/"

"""##Loading Dataset##"""

"""##PreProcessing##

1.   Filter (Band and notch)
2.   Windowing

##Filtering##
"""

def filter_data(data, f, butterworth_order = 4, btype='lowpass', fs=2000):
  emg_data = data.values[:,:12]

  nyquist = fs/2
  if isinstance(f, int):
      fc = f/nyquist
  else:
      fc = list(f)
      for i in range(len(f)):
          fc[i] = fc[i]/nyquist

  b,a = signal.butter(butterworth_order, fc, btype=btype)
  transpose = emg_data.T.copy()

  for i in range(len(transpose)):
      transpose[i] = (signal.lfilter(b, a, transpose[i]))

  filtered = pd.DataFrame(transpose.T)

  return filtered

def notch_filter(data, f0, Q, fs=2000):
    emg_data = data.values[:,:12]

    b, a = signal.iirnotch(f0, Q, fs)
    transpose = emg_data.T.copy()

    for i in range(len(transpose)):
        transpose[i] = (signal.lfilter(b, a, transpose[i]))

    filtered = pd.DataFrame(transpose.T)


    return filtered


"""##Features##


1.   Time Domain
2.   Frequency Domain (Summary Statistics Optional)
3.   Feature Matrix


"""

from tqdm import tqdm

def feature_extractor(features,shape,data):
  l=pd.DataFrame()
  for i,function in enumerate(tqdm(features)):
        feature=[]
        print("Extracting feature....{}".format(str(function)))
        for i in range(data.shape[0]):
          for j in range(data.shape[2]):
                feature.append(function(data[i][:,j]))
        feature = np.reshape(feature,shape)
        l = pd.concat([l,pd.DataFrame(feature)],axis=1)
        print("Done extracting feature....{}".format(str(function)))
        print()
  return l

"""##Time Domain##"""

def rms(data):
  return np.sqrt(np.mean(data**2))

def hist(data, nbins=20):
  histsig, bin_edges = np.histogram(data, bins = nbins)
  return tuple(histsig)

def mdwt(data):
  cA_3, cD_3, cD_2, cD_1 = wavedec(data,'db7', level=3)
  return cA_3

def entropy(data):
  pk = sp.stats.rv_histogram(np.histogram(data, bins=20)).pdf(data)
  return  sp.stats.entropy(pk)

def kurtosis(data):
  return sp.stats.kurtosis(data)

def zero_cross(data):
  return len(np.where(np.diff(np.sign(data)))[0])/len(data)

def min(data):
  return np.min(data)

def max(data):
  return np.max(data)

def mean(data):
  return np.mean(data)

def median(data):
  return np.median(data)

"""##Frequency Domain##"""

def fft(data):
  return np.fft.fft(data)

def psd(data):
  return np.abs(np.fft.fft(data))**2

"""##Feature Matrix##"""
# Dimenstionality Reduction
def pca(data):
    pca=PCA(n_components=600)
    pca.fit(data)
    x_pca=pca.transform(data)
    return pd.DataFrame(x_pca)

"""##Plotting##"""
def get_validation_curve(classifier,parameter,param_range,X,y): # A generalized function to plot validation curve for all 3 classifiers.
  train_scores, test_scores = validation_curve(
    classifier, X, y, param_name=parameter, param_range=param_range,
    scoring="accuracy", n_jobs=1)
  train_scores_mean = np.mean(train_scores, axis=1)
  train_scores_std = np.std(train_scores, axis=1)
  test_scores_mean = np.mean(test_scores, axis=1)
  test_scores_std = np.std(test_scores, axis=1)

  plt.title("Validation Curve with {}".format(classifier.__class__.__name__))
  plt.xlabel(str(parameter))
  plt.ylabel("Score")
  plt.ylim(0.0, 1.1)
  lw = 2
  plt.semilogx(param_range, train_scores_mean, label="Training score",
              color="darkorange", lw=lw)
  plt.fill_between(param_range, train_scores_mean - train_scores_std,
                  train_scores_mean + train_scores_std, alpha=0.2,
                  color="darkorange", lw=lw)
  plt.semilogx(param_range, test_scores_mean, label="Cross-validation score",
              color="navy", lw=lw)
  plt.fill_between(param_range, test_scores_mean - test_scores_std,
                  test_scores_mean + test_scores_std, alpha=0.2,
                  color="navy", lw=lw)
  plt.legend(loc="best")

  return plt

def plot_learning_curve(estimator, title, X, y, axes=None, ylim=None, cv=None,
                        n_jobs=None, train_sizes=np.linspace(.1, 1.0, 5)):
    """
    Generate 3 plots: the test and training learning curve, the training
    samples vs fit times curve, the fit times vs score curve.

    Parameters
    ----------
    estimator : estimator instance
        An estimator instance implementing `fit` and `predict` methods which
        will be cloned for each validation.

    title : str
        Title for the chart.

    X : array-like of shape (n_samples, n_features)
        Training vector, where ``n_samples`` is the number of samples and
        ``n_features`` is the number of features.

    y : array-like of shape (n_samples) or (n_samples, n_features)
        Target relative to ``X`` for classification or regression;
        None for unsupervised learning.

    axes : array-like of shape (3,), default=None
        Axes to use for plotting the curves.

    ylim : tuple of shape (2,), default=None
        Defines minimum and maximum y-values plotted, e.g. (ymin, ymax).

    cv : int, cross-validation generator or an iterable, default=None
        Determines the cross-validation splitting strategy.
        Possible inputs for cv are:

          - None, to use the default 5-fold cross-validation,
          - integer, to specify the number of folds.
          - :term:`CV splitter`,
          - An iterable yielding (train, test) splits as arrays of indices.

        For integer/None inputs, if ``y`` is binary or multiclass,
        :class:`StratifiedKFold` used. If the estimator is not a classifier
        or if ``y`` is neither binary nor multiclass, :class:`KFold` is used.

        Refer :ref:`User Guide <cross_validation>` for the various
        cross-validators that can be used here.

    n_jobs : int or None, default=None
        Number of jobs to run in parallel.
        ``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.
        ``-1`` means using all processors. See :term:`Glossary <n_jobs>`
        for more details.

    train_sizes : array-like of shape (n_ticks,)
        Relative or absolute numbers of training examples that will be used to
        generate the learning curve. If the ``dtype`` is float, it is regarded
        as a fraction of the maximum size of the training set (that is
        determined by the selected validation method), i.e. it has to be within
        (0, 1]. Otherwise it is interpreted as absolute sizes of the training
        sets. Note that for classification the number of samples usually have
        to be big enough to contain at least one sample from each class.
        (default: np.linspace(0.1, 1.0, 5))
    """
    if axes is None:
        _, axes = plt.subplots(1, 3, figsize=(20, 5))

    axes[0].set_title(title)
    if ylim is not None:
        axes[0].set_ylim(*ylim)
    axes[0].set_xlabel("Training examples")
    axes[0].set_ylabel("Score")

    train_sizes, train_scores, test_scores, fit_times, _ = \
        learning_curve(estimator, X, y, cv=cv, n_jobs=n_jobs,
                       train_sizes=train_sizes,
                       return_times=True)
    train_scores_mean = np.mean(train_scores, axis=1)
    train_scores_std = np.std(train_scores, axis=1)
    test_scores_mean = np.mean(test_scores, axis=1)
    test_scores_std = np.std(test_scores, axis=1)
    fit_times_mean = np.mean(fit_times, axis=1)
    fit_times_std = np.std(fit_times, axis=1)

    # Plot learning curve
    axes[0].grid()
    axes[0].fill_between(train_sizes, train_scores_mean - train_scores_std,
                         train_scores_mean + train_scores_std, alpha=0.1,
                         color="r")
    axes[0].fill_between(train_sizes, test_scores_mean - test_scores_std,
                         test_scores_mean + test_scores_std, alpha=0.1,
                         color="g")
    axes[0].plot(train_sizes, train_scores_mean, 'o-', color="r",
                 label="Training score")
    axes[0].plot(train_sizes, test_scores_mean, 'o-', color="g",
                 label="Cross-validation score")
    axes[0].legend(loc="best")

    # Plot n_samples vs fit_times
    axes[1].grid()
    axes[1].plot(train_sizes, fit_times_mean, 'o-')
    axes[1].fill_between(train_sizes, fit_times_mean - fit_times_std,
                         fit_times_mean + fit_times_std, alpha=0.1)
    axes[1].set_xlabel("Training examples")
    axes[1].set_ylabel("fit_times")
    axes[1].set_title("Scalability of the model")

    # Plot fit_time vs score
    axes[2].grid()
    axes[2].plot(fit_times_mean, test_scores_mean, 'o-')
    axes[2].fill_between(fit_times_mean, test_scores_mean - test_scores_std,
                         test_scores_mean + test_scores_std, alpha=0.1)
    axes[2].set_xlabel("fit_times")
    axes[2].set_ylabel("Score")
    axes[2].set_title("Performance of the model")

    return plt

###################### Load Data ##########################
window_len = 400
window_inc = 30
print("(window length, window inc) =", (window_len, window_inc))

aggregate_labels = np.load("aggregate_labels_200ms.npy")
aggregate_test_labels = np.load("aggregate_test_labels_200ms.npy")

reduced_feature_matrix = np.load("reduced_feature_matrix_200ms.npy")
reduced_test_feature_matrix = np.load("reduced_test_feature_matrix_200ms.npy")


print('reduced_feature_matrix and labels loaded')

"""##Classifiers##

1.   Hyperparameter Optimization (GridSearchCV, BayesSearchCV)
2.   SVM
3.   Random Forest
4.   LDA
5.   Learning Curves (includes cross validation, ensures classifier accuracy wasn't a result of the statistical lottery)
6.   Validation Curves (shows the score with respect to some varying hyperparameter, visualize confirmation from hyperparameter optimization)

"""

"""##SVM##"""

# Hyperparameter Tuning for SVM
opt = BayesSearchCV(
    svm.SVC(),
    {'C': (1e-6, 1e+6, 'log-uniform'),
        'gamma': (1e-6, 1e+1, 'log-uniform'),
        'degree': (1, 8),  # integer valued parameter
        'kernel': ['linear', 'poly', 'rbf'],  # categorical parameter
     },
    n_iter=32,
    cv=3
)

opt.fit(reduced_feature_matrix , aggregate_labels)

estimator = opt.best_estimator_

# Save Optimal Model
joblib.dump(estimator,'{}_opt_model_{}{}'.format(estimator.__class__.__name__,int(window_len/2),'ms'))

# Save Report
y_pred= estimator.predict(reduced_test_feature_matrix)
report = classification_report(aggregate_test_labels, y_pred, output_dict=True)
joblib.dump(report,'{}_classification_report_{}{}'.format(estimator.__class__.__name__,int(window_len/2),'ms'))

# Save Plots
################################################################################
# Validation Curve of SVM
param_range = np.logspace(-6, -1, 5)
get_validation_curve(estimator, "gamma",param_range, reduced_feature_matrix , aggregate_labels)
plt.savefig("{}_validation_curve_{}{}.jpg".format(estimator.__class__.__name__,int(window_len/2),'ms'))

# Learning Curve of SVM
fig, axes = plt.subplots(3, 1, figsize=(10, 15))
title = r"Learning Curves (SVM)"
# SVC is more expensive so we do a lower number of CV iterations:
cv = ShuffleSplit(n_splits=10, test_size=0.2, random_state=0)

plot_learning_curve(estimator, title, reduced_feature_matrix , aggregate_labels, axes=axes[:], ylim=(0.7, 1.01),
                    cv=cv, n_jobs=4)

plt.savefig("{}_learning_curve_{}{}.jpg".format(estimator.__class__.__name__,int(window_len/2),'ms'))
################################################################################

"""##Random Forest##"""

# Hyperparameter Tuning for RandomForestClassifier
opt = BayesSearchCV(
    RandomForestClassifier(),
    {'n_estimators': [int(x) for x in np.linspace(start = 100, stop = 2000, num = 20)],
     'max_features': ['auto', 'sqrt'],
     'max_depth': [int(x) for x in np.linspace(10, 110, num = 11)],
     'min_samples_split': [2, 5, 10],
     'min_samples_leaf': [1, 2, 4],
     'bootstrap': [True, False],
     },
    n_iter=32,
    cv=3
)

opt.fit(reduced_feature_matrix, aggregate_labels)

estimator = opt.best_estimator_

# Save Optimal Model
joblib.dump(estimator,'{}_opt_model_{}{}'.format(estimator.__class__.__name__,int(window_len/2),'ms'))

# Save Report
y_pred= estimator.predict(reduced_test_feature_matrix)
report = classification_report(aggregate_test_labels,y_pred, output_dict=True)
joblib.dump(report,'{}_classification_report_{}{}'.format(estimator.__class__.__name__,int(window_len/2),'ms'))

# Save Plots
################################################################################
# Validation Curve of Random Forest Classifier
param_range = np.arange(1, 250, 2)
get_validation_curve(estimator, "n_estimators",param_range, reduced_feature_matrix, aggregate_labels)
plt.savefig("{}_validation_curve_{}{}.jpg".format(estimator.__class__.__name__,int(window_len/2),'ms'))

# Learning Curve of RandomForestClassifier
fig, axes = plt.subplots(3, 1, figsize=(10, 15))
title = r"Learning Curves (RandomForestClassifier)"

cv = ShuffleSplit(n_splits=10, test_size=0.2, random_state=0)

plot_learning_curve(estimator, title, reduced_feature_matrix, aggregate_labels, axes=axes[:], ylim=(0.7, 1.01),
                    cv=cv, n_jobs=4)

plt.savefig("{}_learning_curve_{}{}.jpg".format(estimator.__class__.__name__,int(window_len/2),'ms'))
################################################################################

"""##LDA##"""

# Hyperparameter Tuning for LDA
opt = BayesSearchCV(
    LinearDiscriminantAnalysis(),
    {'solver': ['svd', 'lsqr', 'eigen'],
    },
    n_iter=32,
    cv=3
)

opt.fit(reduced_feature_matrix, aggregate_labels)

estimator = opt.best_estimator_

# Save Optimal Model
joblib.dump(estimator,'{}_opt_model_{}{}'.format(estimator.__class__.__name__,int(window_len/2),'ms'))

# Save Report
y_pred= estimator.predict(reduced_test_feature_matrix)
report = classification_report(aggregate_test_labels, y_pred, output_dict=True)
joblib.dump(report,'{}_classification_report_{}{}'.format(estimator.__class__.__name__,int(window_len/2),'ms'))

# Save Plots
################################################################################
# Validation Curve of LDA
grid= ['svd', 'lsqr', 'eigen']
get_validation_curve(estimator,'solver' ,grid, reduced_feature_matrix, aggregate_labels)
plt.savefig("{}_validation_curve_{}{}.jpg".format(estimator.__class__.__name__,int(window_len/2),'ms'))

# Learning Curve of LDA
fig, axes = plt.subplots(3, 1, figsize=(10, 15))
title = r"Learning Curves (LDA)"

cv = ShuffleSplit(n_splits=10, test_size=0.2, random_state=0)

plot_learning_curve(estimator, title, reduced_feature_matrix, aggregate_labels, axes=axes[:], ylim=(0.7, 1.01),
                    cv=cv, n_jobs=4)

plt.savefig("{}_learning_curve_{}{}.jpg".format(estimator.__class__.__name__,int(window_len/2),'ms'))
################################################################################
